In [1]:
import numpy as np
import pandas as pd

* Please implement the following tasks:

1. A csv file containing the dataset will be shared, download it and upload it.

2. Read the csv file using Pandas.

In [2]:
my_path = "/content/classwork-data.csv" # write the path of the data file here
data = pd.read_csv(my_path)

In [3]:
data.head()

Unnamed: 0  col1       col2         col3           col4      target
0           0   1.0  73.847017  5453.381922  402715.987625  241.893563
1           1   1.0  68.781904  4730.950324  325403.771243  162.310473
2           2   1.0  74.110105  5492.307721  407035.504061  212.740856
3           3   1.0  71.730978  5145.333263  369079.789145  220.042470
4           4   1.0  69.881796  4883.465393  341265.331673  206.349801

In [5]:
data.shape

(10000, 6)

3. Create a variable X for the input columns (col1, col2, col3, col4).

In [6]:
X = data.iloc[:,1:-1].values

In [7]:
X.shape

(10000, 4)

4. Create a variable Y for the output column (target).

In [8]:
Y  = data.iloc[:,-1].values

In [16]:
Y.shape

(10000,)

In [ ]:
#################################################################################################################

5. Split the dataset into two sets, training and test sets.
* check online [here](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html) how to use the **train_test_split** function in the sklearn library.

In [13]:
# You need to find:   X_train, X_test, Y_train, Y_test
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.20, random_state=42)

In [18]:
X_train.shape

(8000, 4)

In [20]:
X_test.shape

(2000, 4)

In [21]:
len(X)

10000

6. Use Mean squared error to report the performance of the linear regression model.

$$
MSE = \frac{\sum{(target - prediction)^2}}{n}
$$

In [22]:
# define the MSE fun
def MSE(y_true, y_pred):
  n = len(X)
  nume= ((y_true - y_pred)**2)
  s = np.sum(nume)
  MSE = s/n
  return MSE 
  # calculate the MSE and return it

In [ ]:
#################################################################################################################

7. Implement function MLE, that computes the maximum likelihood estimator for the given data.

Calculate the model parameter using the closed form solution as indicated in the following equation:

$$
\boldsymbol w = (\boldsymbol X^T\boldsymbol X)^{-1}\boldsymbol X^T\boldsymbol Y
$$

X is the inputs, and Y is the targets

In [37]:
def MLE(inputs, targets):
  A = inputs.transpose() @ inputs
  B = inputs.transpose() @ targets
  w = np.linalg.inv(A) @ B
  return w
  # calculate the parameter w and return it
  #pass

In [45]:
c =np.array([[1,2],[3,4]])
d =np.array([[1],[2]])
np.linalg.inv(c)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [47]:
c@d

array([[ 5],
       [11]])

In [ ]:
#################################################################################################################

Lets evaluate the model by taking one example from the test data, and then calculate the MSE between the model prediction and the target.

In [38]:
w = MLE(X_train, Y_train)# All the parameter estimation should be done using 
                         # only the training data.

In [39]:
w

array([ 1.92947048e+01, -4.78485154e+00,  1.57018602e-01, -7.60718961e-04])

In [40]:
Y_pred = X_test @ w

In [44]:
Y_pred

array([165.62541218, 185.77534783, 171.15382306, ..., 126.73576242,
       175.18063772, 105.91295871])

In [41]:
print(MSE(Y_test, Y_pred))

20.25920465820746


# New Section

In [ ]:
#################################################################################################################